# Anjelica's HWDB entries

# The `bitstream_tar` field references the file path to the `<name>.tar.gz` files found in
# `results-build` directory. The name of `<name>.tar.gz` is the same as the name of the
# their corresponding hwdb entries. 

# Change the `bitstream_tar` field to the correct path to the tar.gz file in your chipyard directory.

alveo_u280_firesim_gemmini_rocket_singlecore_no_nic:
    bitstream_tar: #/results-build/alveo_u280_firesim_gemmini_rocket_singlecore_no_nic.tar.gz
    deploy_quintuplet_override: null
    custom_runtime_config: null

alveo_u280_firesim_mediumgemmini_rocket_singlecore_no_nic:
    bitstream_tar: #/results-build/alveo_u280_firesim_mediumgemmini_rocket_singlecore_no_nic.tar.tar.gz
    deploy_quintuplet_override: null
    custom_runtime_config: null

alveo_u280_firesim_printfgemmini_rocket_singlecore_no_nic:
    bitstream_tar: #/results-build/alveo_u280_firesim_printfgemmini_rocket_singlecore_no_nic.tar.gz
    deploy_quintuplet_override: null
    custom_runtime_config: null