# Anjelica's configs

# the TargetConfigs can be found in TargetConfigs.scala
alveo_u280_firesim_gemmini_rocket_singlecore_no_nic:
    PLATFORM: xilinx_alveo_u280
    TARGET_PROJECT: firesim
    DESIGN: FireSim
    TARGET_CONFIG: FireSimLeanGemminiRocketConfig
    PLATFORM_CONFIG: BaseXilinxAlveoU280Config
    deploy_quintuplet: null
    platform_config_args:
        fpga_frequency: 60
        build_strategy: TIMING
    post_build_hook: null
    metasim_customruntimeconfig: null
    bit_builder_recipe: bit-builder-recipes/xilinx_alveo_u280.yaml

alveo_u280_firesim_printfgemmini_rocket_singlecore_no_nic:
    PLATFORM: xilinx_alveo_u280
    TARGET_PROJECT: firesim
    DESIGN: FireSim
    TARGET_CONFIG: WithAutoCounter_FireSimLeanGemminiPrintfRocketConfig
    PLATFORM_CONFIG: BaseXilinxAlveoU280Config
    deploy_quintuplet: null
    platform_config_args:
        fpga_frequency: 60
        build_strategy: TIMING
    post_build_hook: null
    metasim_customruntimeconfig: null
    bit_builder_recipe: bit-builder-recipes/xilinx_alveo_u280.yaml

alveo_u280_firesim_mediumgemmini_rocket_singlecore_no_nic:
    PLATFORM: xilinx_alveo_u280
    TARGET_PROJECT: firesim
    DESIGN: FireSim
    TARGET_CONFIG: FireSimMediumGemminiRocketConfig
    PLATFORM_CONFIG: BaseXilinxAlveoU280Config
    deploy_quintuplet: null
    platform_config_args:
        fpga_frequency: 60
        build_strategy: TIMING
    post_build_hook: null
    metasim_customruntimeconfig: null
    bit_builder_recipe: bit-builder-recipes/xilinx_alveo_u280.yaml